# ----------------------------------------------------
# request

# 请求头
CommonRequest request

# 请求相机开关状态
# true(open)
# false(close)
bool camera_enabled

---

# ----------------------------------------------------
# response

# 响应头
CommonResponse response

# 当前相机开关状态
bool camera_enabled
