# -----------------------------------------------------------------------------------
# 机器人运控状态 - 动作运行信息
# -----------------------------------------------------------------------------------

McPlayerState player_state             # 动作运行状态

McControlArea control_area             # 控制区域

string motion                          # 动作名称

McMotionType type                      # 动作类型

McMotionIntrInfo intr_info             # 动作断点信息

int32 current_steps                    # 当前动作执行进度
